<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-02T23:55:07 IST" name="Suite" finished-at="2024-09-02T23:55:43 IST" duration-ms="36012">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" name="LoginErrorValidation" class="ChaitraAcademy.tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-09-02T23:55:07 IST" name="Submit order test" finished-at="2024-09-02T23:55:30 IST" duration-ms="22754">
      <class name="ChaitraAcademy.tests.SubmitOrderTestTestdataprosample">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:07 IST" name="launchApplication" finished-at="2024-09-02T23:55:10 IST" duration-ms="3193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:10 IST" name="SubmitOrder" finished-at="2024-09-02T23:55:27 IST" duration-ms="17246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:27 IST" name="tearDown" finished-at="2024-09-02T23:55:27 IST" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:27 IST" name="launchApplication" finished-at="2024-09-02T23:55:29 IST" duration-ms="1671" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:29 IST" name="OrderHistoryTest" finished-at="2024-09-02T23:55:30 IST" depends-on-methods="ChaitraAcademy.tests.SubmitOrderTestTestdataprosample.SubmitOrder" duration-ms="476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTestTestdataprosample@73eb439a]" started-at="2024-09-02T23:55:30 IST" name="tearDown" finished-at="2024-09-02T23:55:30 IST" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ChaitraAcademy.tests.SubmitOrderTestTestdataprosample -->
    </test> <!-- Submit order test -->
    <test started-at="2024-09-02T23:55:30 IST" name="Error Validation test" finished-at="2024-09-02T23:55:43 IST" duration-ms="12984">
      <class name="ChaitraAcademy.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:30 IST" name="launchApplication" finished-at="2024-09-02T23:55:32 IST" duration-ms="1700" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:32 IST" name="LoginErrorValidation" finished-at="2024-09-02T23:55:33 IST" duration-ms="876" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ChaitraAcademy.tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:33 IST" name="tearDown" finished-at="2024-09-02T23:55:33 IST" duration-ms="71" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:33 IST" name="launchApplication" finished-at="2024-09-02T23:55:34 IST" duration-ms="1664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:34 IST" name="LoginErrorValidation" finished-at="2024-09-02T23:55:35 IST" duration-ms="409" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ChaitraAcademy.tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:35 IST" name="tearDown" finished-at="2024-09-02T23:55:35 IST" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:35 IST" name="launchApplication" finished-at="2024-09-02T23:55:37 IST" duration-ms="1667" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:37 IST" name="ProductErrorValidation" finished-at="2024-09-02T23:55:43 IST" duration-ms="6248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@4dc27487]" started-at="2024-09-02T23:55:43 IST" name="tearDown" finished-at="2024-09-02T23:55:43 IST" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ChaitraAcademy.tests.ErrorValidation -->
    </test> <!-- Error Validation test -->
  </suite> <!-- Suite -->
</testng-results>
